Hw 14
e1cb4ac37s/test-guru pull request #13
Opened 2020-09-20 12:05 UTC by e1cb4ac37s

2020-09-20 18:08 UTC, BubuntuClu requested changes

2020-09-20 18:08 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +    flash_options = if result.html_url
в октоките есть метод last_response, на его основе стоит сделать метод `success?` и только при успехе создавать у себя запись

2020-09-20 18:08 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +    byebug
это надо убрать

2020-09-20 18:08 UTC, BubuntuClu commented on lib/clients/github_client.rb
> +end
в IDE сделай настройку, чтобы добавлялась пустая строка в файл

2020-09-20 18:08 UTC, BubuntuClu commented on config/credentials.yml.enc
> +TeoLqsp4v2FyWyYuLfBVwhLluk/Q3rvmOOK8Tilff1ryXSXLh8T5W1birQzB7S48bxKfRLxXF7I7oiwDPLkl+4/Z5xodR4o19ZAOAGYqsO/9aoZWmhstFiiNGNe07dnEoxGdUb3Ku3NMfTLIyXiLK8VJP4iVVXdXfB45AN+1DJP4MDCPlXg3bizDn3oaZ/ReHuxVEKP
нет, это не тоже самое что и .env
тут все равно видно твои ключи секретные. энвы не должны попадать в репу

2020-09-20 18:08 UTC, BubuntuClu commented on config/application.rb
> +    config.autoload_paths << "#{Rails.root}/lib/clients"
это можно удалить как и самописный сервис

2020-09-20 18:08 UTC, BubuntuClu commented on app/models/gist.rb
> +class Gist
не понял назначение этого класса и GistsService

2020-09-20 18:08 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +    result = GistQuestionService.new(@test_passage.current_question, current_user).call
а где гист в твоем приложении создается?

2020-09-21 03:03 UTC, e1cb4ac37s commented on config/credentials.yml.enc
> +TeoLqsp4v2FyWyYuLfBVwhLluk/Q3rvmOOK8Tilff1ryXSXLh8T5W1birQzB7S48bxKfRLxXF7I7oiwDPLkl+4/Z5xodR4o19ZAOAGYqsO/9aoZWmhstFiiNGNe07dnEoxGdUb3Ku3NMfTLIyXiLK8VJP4iVVXdXfB45AN+1DJP4MDCPlXg3bizDn3oaZ/ReHuxVEKP
Без master.key то что Вы там видите - бесполезно.

2020-09-21 03:04 UTC, e1cb4ac37s commented on app/models/gist.rb
> +class Gist
Ответ ниже.

2020-09-21 03:17 UTC, e1cb4ac37s commented on app/controllers/test_passages_controller.rb
> +    result = GistQuestionService.new(@test_passage.current_question, current_user).call
Я мог у current_user добавить ассоциацию gists и туда их записывать. А я этого не сделал потому что это gists, и суть их в том что они на гитхабе. Если я зайду на гитхаб и удалю там гист - в таблице gists приложения ничего не изменится, это рассинхрон. Поэтому гистов нету в БД, они создаются с description: TestGuru/test.title:::question.body(25):::current_user.email, который парсится в классе Gist. GistService запрашивает список гистов с моего аккаунта в гитхабе, парсит и сохраняет только url, email, title, после чего этот список рендерит у админа, админ может смотреть кто инициировал создание того или иного gist.
Ответ на вопрос: нигде, только на гитхабе. И список потом тянетс яне из бд а из гитхаба.

2020-09-22 18:04 UTC, merged