Hw 10
e1cb4ac37s/test-guru pull request #9
Opened 2020-09-07 05:34 UTC by e1cb4ac37s

1. Я не уверен что все правильно делаю с редиректом в url с которого было перенаправление на логин. Попросил бы это проверить. И вообще правильно ли тут работа с куками/сессиями ведется.
2. Flash вынес не в хэлпер а в partial, не уверен что мне тут нужен хэлпер.

2020-09-07 07:18 UTC, BubuntuClu requested changes

2020-09-07 07:18 UTC, BubuntuClu commented on app/controllers/application_controller.rb
> +  def save_url
не уверен я в надобности этих методов. да и ты тоже. у тебя есть clear_saved_url, а ты его не используешь и пишешь зануление вручную

2020-09-07 07:18 UTC, BubuntuClu commented on app/controllers/sessions_controller.rb
> +      if saved_url.present?
вместо этого ifa просто `redirect_to saved_url || root_path`

2020-09-07 07:18 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +  before_action :authenticate_user!
это можно добавить в application_controller, раз в большинстве контроллеров тебе это нужно. а где не нужно исключить выполнение этого метода

2020-09-07 07:18 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
>    def set_user
этот метод уже не нужен. используй метод `current_user`

2020-09-07 07:18 UTC, BubuntuClu commented on app/models/validators/email_validator.rb
> +class EmailValidator < ActiveModel::EachValidator
шот костыль какой-то. используй стандартный валидатор почты из URI. а этот класс не нужен будет

2020-09-07 07:18 UTC, BubuntuClu commented on db/migrate/20200806045413_create_users.rb
> -      t.string :first_name
вот так делать нельзя. нужно создавать новую миграцию и удалять поля. то что ты задним числом откатил у себя эти строки в таблице, не значит что у других откатиться. у остальных эти миграции уже накачены и они не трекаются

2020-09-07 07:18 UTC, BubuntuClu commented on db/migrate/20200806045723_not_null_constraint.rb
> -    change_column_null :users, :first_name, false
аналогично и тут

2020-09-08 16:11 UTC, e1cb4ac37s commented on app/controllers/tests_controller.rb
> +    params.require(:test).permit(:title, :level, :category_id, :author_id)
Этот кусок кода походу не до конца рабочий, правильно ли будет его переписать так?
`params.require(:test).permit(:title, :level, :category_id).merge(author_id: current_user.id)`

2020-09-09 02:20 UTC, merged